unbind r
bind r source-file ~/.tmux.conf\; display-message "Config reloaded..." 

set -g prefix C-s

# vim keybindings
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

unbind %
bind '\' split-window -h

unbind '"'
bind '|' split-window -v

set -g mouse on

# Plugins
# ==================================================

# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-battery'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'frappe' # or frappe, macchiato, mocha
set -g @catppuccin_status_modules_right "battery date_time application session"

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


