unbind r
bind r source-file ~/.tmux.conf\; display-message "Config reloaded..." 

set -g prefix M-b

# vim keybindings
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

unbind %
bind '\' split-window -h

unbind '"'
bind '|' split-window -v

set -g mouse on

# ==================================================
# 		Alt bindings
# ==================================================

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-w choose-window
bind -n M-s choose-session

bind -n 'M-\' split-window -h -c "#{pane_current_path}"
bind -n 'M-|' split-window -v -c "#{pane_current_path}"
bind -n M-x confirm-before "kill-pane"
bind -n M-z resize-pane -Z

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8

bind -n M-9 switch-client -p # `9` is for `(`
bind -n M-0 switch-client -n # `0` is for `)`

bind -n M-c new-window -c "#{pane_current_path}"
bind -n M-q confirm-before "kill-window"
bind -n M-r command-prompt -I'#W' { rename-window -- '%%' }
bind -n M-p previous-window
bind -n M-n next-window

bind -n M-C new-session
bind -n M-Q confirm-before "kill-session"
bind -n M-R command-prompt -I'#S' { rename-session -- '%%' }
# bind -n M-P previous-session
# bind -n M-N next-session

bind -n M-: command-prompt
bind -n M-/ list-keys 

bind -n M-d confirm-before "detach"

bind -n M-k clear-history
bind -n M-[ copy-mode

# TODO: change working directory
# use `attach -c <path>`
bind -n M-~ command-prompt -p "Change working directory" "attach -c '%%'"

# set -g @resurrect-save 'S'
# set -g @resurrect-restore 'R'

# ==================================================
# 			Plugins
# ==================================================

# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-battery'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'frappe' # latte, frappe, macchiato, mocha
set -g @catppuccin_status_modules_right "battery date_time application session"

# set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


