UP add volume 2
DOWN add volume -2
LEFT seek -5
RIGHT seek 5
j seek -10
l seek 10
J seek -60
L seek 60
k cycle pause
[ multiply speed 0.840896415253715
] multiply speed 1.189207115002721

n cycle sub
m cycle audio
ctrl+r load-config-file "~~/mpv.conf" ; load-input-conf "~~/input.conf" ; show-text "Config + keys reloaded" 2000
