# General behavior
force-window=yes
save-position-on-quit=yes
save-watch-history=yes
screenshot-dir=~/.config/mpv/screenshots

# Languages
alang=eng,en,ukr,rus
slang=eng,en,ukr,rus

# OSD
osd-duration=2000
osd-font="Helvetica Neue"
osd-font-size=24
osd-color=0.8/0.8

# Subtitles
sub-auto=fuzzy
sub-font="Helvetica Neue"
sub-color=0.5/0.5
sub-font-size=36
sub-border-size=2

# Mac
# native-fs=no
macos-force-dedicated-gpu=yes

# Video settings
vo=gpu-next
gpu-api=vulkan
hwdec=auto
vulkan-async-compute=yes
vulkan-async-transfer=yes


hwdec=auto

target-colorspace-hint=yes
icc-profile-auto=no
hdr-compute-peak=yes

tone-mapping=mobius
target-contrast=auto

#cocoa-cb-output-csp=bt.709
#target-prim=bt.709
#target-trc=bt.1886

[sdr]
#cocoa-cb-output-csp=bt.709
#target-prim=bt.709
#target-trc=bt.1886

[hdr]
#cocoa-cb-output-csp=bt.2020
#target-prim=bt.2020
#target-trc=pq
